name: Build Sim Serial Interface 

on:
  push:
    paths: 
      - 'sim-interface/**'
  pull_request:
    paths:
      - 'sim-interface/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: make
      run: make
      working-directory: sim-interface/